- name: Create database
  ansible.mysql.mysql_db:
    name: "{{ db_maria_name }}"
    state: present
    login_unix_socket: "{{ db_maria_socket }}"

- name: Create user and grant privileges
  ansible.mysql.mysql_user:
    name: "{{ db_maria_user }}"
    password: "{{ db_maria_password }}"
    priv: "{{ db_maria_name }}.*:ALL"
    host: "{{ db_maria_allowed_host }}"
    state: present
    login_unix_socket: "{{ db_maria_socket }}"
    column_case_sensitive: false
