---
- name: Change hostname in datadog
  ansible.builtin.lineinfile:
    path: /etc/datadog-agent/datadog.yaml
    regexp: '^hostname:'
    line: "hostname: {{ ansible_hostname }}"
  notify: Restart Datadog
