---
- name: Install certbot
  hosts: webservers
  become: true
  tasks:
    - name: Install certbot on Ubuntu
      ansible.builtin.apt:
        name:
          - certbot
          - python3-certbot-nginx
        state: present
        update_cache: true
      when: ansible_os_family == "Ubuntu"
