---
- name: Restart Nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Restart consul-template
  ansible.builtin.systemd:
    name: consul-template
    state: restarted
    daemon_reload: yes

- name: Reload consul
  ansible.builtin.systemd:
    name: consul
    state: reloaded

- name: Restart Datadog
  ansible.builtin.service:
    name: datadog-agent
    state: restarted
