- name: Configure consul.hcl
  ansible.builtin.template:
    src: consul.hcl.j2
    dest: "{{ consul_config_dir }}/consul.hcl"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: '0640'
  notify: Restart consul

- name: Add conf.yaml
  ansible.builtin.template:
    src: conf.yaml.j2
    dest: "{{ consul_config_dir }}/conf.yaml"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: '0640'
  notify: Restart consul
