---
- name: Install unzip package
  ansible.builtin.apt:
    name: unzip
    state: present
    update_cache: yes
  become: yes

- name: Create consul system group
  ansible.builtin.group:
    name: "{{ consul_group }}"
    system: yes
  become: yes

- name: Create consul system group and user
  ansible.builtin.user:
    name: "{{ consul_user }}"
    group: "{{ consul_group }}"
    system: yes
    shell: /bin/false
  become: yes

- name: Download and unzip Consul
  ansible.builtin.unarchive:
    src: "{{ consul_download_url }}"
    dest: /usr/local/bin
    remote_src: yes
    mode: '0755'
    owner: root
    group: root
  become: yes

- name: Create Consul directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: '0755'
  loop:
  - "{{ consul_data_dir }}"
  - "{{ consul_config_dir }}"
  become: yes
