---
- name: Restart consul
  ansible.builtin.systemd:
    name: consul
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Restart Datadog
  ansible.builtin.service:
    name: datadog-agent
    state: restarted
