plugin: amazon.aws.aws_ec2
regions:
  - us-east-1

hostnames:
  - instance-id

use_contrib_script_compatible_sanitization: True
use_contrib_script_compatible_ec2_tag_keys: True

filters:
  instance-state-name: running
  tag:Environment: Dev

compose:
  ansible_host: private_ip_address

keyed_groups:
  - key: tags.Role
    separator: ""
