all:
  children:
    consul_servers:
      hosts:
        consul:
          ansible_host: 192.168.1.111

web:
  hosts:
    app2:
      ansible_host: 192.168.1.109
    app1:
      ansible_host: 192.168.1.108

lbs:
  hosts:
    lb:
      ansible_host: 192.168.1.107

db:
  hosts:
    mariadb:
      ansible_host: 192.168.1.110

allhosts:
  children:
    consul_servers:
    web:
    lbs:
    db:
